#!/usr/bin/env sh

# Set good defaults to allow script to be run by hand. The two variables below
# will never be used when run from within the Docker hub.
DOCKER_REPO=${DOCKER_REPO:-"efrecon/act"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

# Minimum version of bat to build for.
MINVER=${MINVER:-0.0.1}

# You shouldn't really need to have to modify the following variables.
GH_API=https://api.github.com/
GH_PROJECT=nektos/act

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

gh_tags() {
  download=$(_img_downloader)
  if [ -z "$download" ]; then
    return 1
  else
    $download "${GH_API%/}/repos/${GH_PROJECT}/releases" |
      grep -oE '[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"(v[0-9]+\.[0-9]+\.[0-9]+)"' |
      sed -E 's/[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"(v[0-9]+\.[0-9]+\.[0-9]+)"/\1/'
  fi
}

for tag in $(gh_tags|sort); do
  if [ "$(img_version "${tag#v}")" -ge "$(img_version "$MINVER")" ]; then
    if docker image inspect "${DOCKER_REPO}:$tag" >/dev/null 2>&1; then
      echo "============== Pushing ${DOCKER_REPO}:$tag"
      docker push "${DOCKER_REPO}:$tag"
    else
      echo "!!!!!!!!!!!!!! ${DOCKER_REPO}:$tag was not built, cannot push!"
    fi
  fi
done