#!/usr/bin/env sh

# Set good defaults to allow script to be run by hand. The two variables below
# will never be used when run from within the Docker hub.
DOCKER_REPO=${DOCKER_REPO:-"efrecon/vcluster"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

# helm version, when empty, the default, this will be the latest stable
# version at the time of the build. There also must be a version of the
# efrecon/kubectl image at this version at the time of the build.
HELM_VERSION=

GH_API=https://api.github.com/
GH_PROJECT=loft-sh/vcluster

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

gh_tags() {
  download=$(_img_downloader)
  if [ -z "$download" ]; then
    return 1
  else
    $download "${GH_API%/}/repos/$1/releases" |
      grep -oE '[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"(v[0-9]+\.[0-9]+\.[0-9]+)"' |
      sed -E 's/[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"(v[0-9]+\.[0-9]+\.[0-9]+)"/\1/'
  fi
}

[ -z "$HELM_VERSION" ] && HELM_VERSION=$(gh_tags "helm/helm" | head -n 1)

# Login at the Docker hub to be able to access info about the image.
token=$(img_auth "$DOCKER_REPO")

echo "============== Gettings latest releases for $GH_PROJECT at github"
for tag in $(gh_tags "$GH_PROJECT"); do
  # Get the revision out of the org.opencontainers.image.revision label, this
  # will be the label where we store information about this repo (it cannot be
  # the tag, since we tag as the base image).
  revision=$(img_labels --verbose --token "$token" -- "$DOCKER_REPO" "$tag" |
              grep "^org.opencontainers.image.revision" |
              sed -E 's/^org.opencontainers.image.revision=(.+)/\1/')
  # If the revision is different from the source commit (including empty,
  # which will happen when our version of the image does not already exist),
  # build the image, making sure we label with the git commit sha at the
  # org.opencontainers.image.revision OCI label, but using the same tag as the
  # library image.
  if [ "$revision" != "$SOURCE_COMMIT" ]; then
    echo "============== No ${DOCKER_REPO}:$tag at $SOURCE_COMMIT"
    docker build \
      --build-arg HELM_VERSION="$HELM_VERSION" \
      --build-arg VCLUSTER_VERSION="$tag" \
      --tag "${DOCKER_REPO}:$tag" \
      --label "org.opencontainers.image.revision=$SOURCE_COMMIT" \
      .
  fi
done