name: bat

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/github-workflows'
  schedule:
      - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: printf %s\\n "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/build
      -
        name: Build Docker hub images
        env:
          DOCKER_REPO: docker.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/push
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/push