name: bat

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'bat/**'
      - '.github/workflows/bat.yml'
  schedule:
      - cron: "0 0 * * *"

jobs:
  bat:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/push
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/build
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/bat
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd bat && ./hooks/push
      -
        # Note: This uses the password, not the token as this action would
        # otherwise not work.
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: efrecon/bat
          short-description: A cat(1) clone with wings
          readme-filepath: ./bat/README.md