name: disque

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'disque/**'
      - '.github/workflows/disque.yml'

jobs:
  disque:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Docker Hub image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            DISQUE_VERSION=1.0-rc1
          context: disque
          push: true
          tags: efrecon/disque:1.0-rc1

