name: jq

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/github-workflows'
    paths:
      - 'jq/**'
      - '.github/workflows/jq.yml'
  schedule:
      - cron: "0 0 * * *"

jobs:
  jq:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/jq
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd jq && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/jq
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd jq && ./hooks/push
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/jq
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd jq && ./hooks/build
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/jq
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd jq && ./hooks/push