name: mqtt

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/github-workflows'
    paths:
      - 'mqtt/**'
      - '.github/workflows/mqtt.yml'
  schedule:
      - cron: "0 0 * * *"

jobs:
  mqtt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Docker Hub image
        uses: docker/build-push-action@v2
        env:
          MOSQUITTO_VERSION: 1.6.9
        with:
          context: mqtt-client
          push: true
          build-args: |
            ALPINE_VERSION=3.12
            MOSQUITTO_VERSION=${{ env.MOSQUITTO_VERSION }}
            PACKAGE_RELEASE=1
          tags: efrecon/mqtt-client:${{ env.MOSQUITTO_VERSION }}

