name: mqtt

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/github-workflows'
    paths:
      - 'mqtt/**'
      - '.github/workflows/mqtt.yml'
  schedule:
      - cron: "0 0 * * *"

jobs:
  bat:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Docker Hub image
        uses: docker/build-push-action@v2
        with:
          context: mqtt-client
          push: true
          tags: efrecon/mqtt-client

