name: ts-node

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'ts-node/**'
      - '.github/workflows/ts-node.yml'
  schedule:
      - cron: "0 0 * * *"

jobs:
  ts-node:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/ts-node
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd ts-node && ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/ts-node
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd ts-node && ./hooks/push
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/ts-node
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd ts-node && ./hooks/build
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/ts-node
          SOURCE_COMMIT: ${{ github.sha }}
        run: cd ts-node && ./hooks/push
      -
        # Note: This uses the password, not the token as this action would
        # otherwise not work.
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: efrecon/ts-node
          short-description: TypeScript execution and REPL for node.js.
          readme-filepath: ./ts-node/README.md