#!/usr/bin/env sh

im="abiosoft/caddy"
MINVER=${MINVER:-0.11}

# shellcheck disable=SC1090
. "$(dirname "$0")/docker_tags/docker_tags.sh"
# shellcheck disable=SC1090
. "$(dirname "$0")/newtags.sh"

# From: https://stackoverflow.com/a/37939589
version() {
    echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
}


IMG=$(basename "$DOCKER_REPO")
for tag in $(newtags "$im" "$DOCKER_REPO" '[0-9]+(\.[0-9]+)+$'); do
    if [ "$(version "$tag")" -ge "$(version "$MINVER")" ]; then
        echo "============== Building ${IMG}:$tag"
        docker build --build-arg version="$tag" -t "${DOCKER_REPO}:$tag" .
    fi
done
