#!/usr/bin/env sh

im="abiosoft/caddy"
MINVER=${MINVER:-0.11}

# shellcheck disable=SC1090
. "$(dirname "$0")/reg-tags/image_tags.sh"


for tag in $(img_tags --filter '[0-9]+(\.[0-9]+)+$' --verbose -- "$im"); do
    if [ "$(img_version "$tag")" -ge "$(img_version "$MINVER")" ]; then
        echo "============== Building ${DOCKER_REPO}:$tag"
        docker build --build-arg version="$tag" -t "${DOCKER_REPO}:$tag" .
    fi
done
