#!/usr/bin/env sh

im="abiosoft/caddy"
MINVER=${MINVER:-0.11}

# shellcheck disable=SC1090
. "$(dirname "$0")/docker_tags/docker_tags.sh"
# shellcheck disable=SC1090
. "$(dirname "$0")/newtags.sh"


for tag in $(newtags --filter '[0-9]+(\.[0-9]+)+$' -- "$im" "$DOCKER_REPO"); do
    if [ "$(version "$tag")" -ge "$(version "$MINVER")" ]; then
        echo "============== Pushing ${DOCKER_REPO}:$tag"
        docker push "${DOCKER_REPO}:$tag"
    fi
done